apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sample
  name: sample-hello-v2
  labels:
    app: frontend-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-v2
  template:
    metadata:
      labels:
        app: frontend-v2
    spec:
      containers:
      - name: frontend-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080

